/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SupplyChain {
  export type ClosureReportStruct = {
    recalled: boolean;
    quantity: BigNumberish;
    quarantined: BigNumberish;
    claimed: BigNumberish;
    claimedBeforeSale: BigNumberish;
    unaccounted: BigNumberish;
    holdersTotal: BigNumberish;
    holdersAcknowledged: BigNumberish;
    holdersEscalated: BigNumberish;
    holdersPending: BigNumberish;
    deadline: BigNumberish;
  };

  export type ClosureReportStructOutput = [
    recalled: boolean,
    quantity: bigint,
    quarantined: bigint,
    claimed: bigint,
    claimedBeforeSale: bigint,
    unaccounted: bigint,
    holdersTotal: bigint,
    holdersAcknowledged: bigint,
    holdersEscalated: bigint,
    holdersPending: bigint,
    deadline: bigint
  ] & {
    recalled: boolean;
    quantity: bigint;
    quarantined: bigint;
    claimed: bigint;
    claimedBeforeSale: bigint;
    unaccounted: bigint;
    holdersTotal: bigint;
    holdersAcknowledged: bigint;
    holdersEscalated: bigint;
    holdersPending: bigint;
    deadline: bigint;
  };
}

export interface SupplyChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DISTRIBUTORS"
      | "MAX_BATCH_QUANTITY"
      | "MAX_QUARANTINE_PER_TX"
      | "PRODUCERS"
      | "ProductStock"
      | "SELLERS"
      | "SUPPLIERS"
      | "ackRecall"
      | "actorId"
      | "addActor"
      | "addDistributor"
      | "addProducer"
      | "addProduct"
      | "addSeller"
      | "addSupplier"
      | "claimDigest"
      | "claimUnit"
      | "claimUnitFor"
      | "claimedBeforeSaleCount"
      | "claimedCount"
      | "closureReport"
      | "distributeProduct"
      | "distributorCtr"
      | "escalate"
      | "getRecallHolders"
      | "holderStatus"
      | "listForSale"
      | "markProductSold"
      | "missedRecalls"
      | "owner"
      | "processProduct"
      | "producerCtr"
      | "productCtr"
      | "quarantineUnits"
      | "quarantinedCount"
      | "recall"
      | "recallWindow"
      | "recalls"
      | "sellerCtr"
      | "setRecallWindow"
      | "showStage"
      | "supplierCtr"
      | "supplyProduct"
      | "unitLeaf"
      | "unitStatus"
      | "units"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActorAdded"
      | "BatchRecalled"
      | "BatchRegistered"
      | "ProductAdded"
      | "ProductStageUpdated"
      | "RecallAcknowledged"
      | "RecallEscalated"
      | "RecallWindowUpdated"
      | "UnitClaimed"
      | "UnitsQuarantined"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DISTRIBUTORS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_BATCH_QUANTITY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_QUARANTINE_PER_TX",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRODUCERS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ProductStock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "SELLERS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "SUPPLIERS",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ackRecall",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "actorId",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addActor",
    values: [AddressLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addDistributor",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addProducer",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addProduct",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addSeller",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "addSupplier",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDigest",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimUnit",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimUnitFor",
    values: [
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike[],
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claimedBeforeSaleCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimedCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closureReport",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributorCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "escalate",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecallHolders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "holderStatus",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listForSale",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markProductSold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "missedRecalls",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "producerCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "productCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quarantineUnits",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "quarantinedCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recall",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recallWindow",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recalls",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "sellerCtr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setRecallWindow",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "showStage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supplierCtr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supplyProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unitLeaf",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unitStatus",
    values: [BigNumberish, BigNumberish, BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "units",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DISTRIBUTORS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_BATCH_QUANTITY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_QUARANTINE_PER_TX",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PRODUCERS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ProductStock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "SELLERS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SUPPLIERS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ackRecall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "actorId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addActor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addDistributor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addProducer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addProduct", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addSeller", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addSupplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimDigest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimUnit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimUnitFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimedBeforeSaleCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimedCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "closureReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributorCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "escalate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRecallHolders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "holderStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listForSale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markProductSold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "missedRecalls",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "producerCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "productCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quarantineUnits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quarantinedCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recallWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recalls", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sellerCtr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRecallWindow",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "showStage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supplierCtr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supplyProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unitLeaf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unitStatus", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "units", data: BytesLike): Result;
}

export namespace ActorAddedEvent {
  export type InputTuple = [
    actorId: BigNumberish,
    role: BigNumberish,
    actor: AddressLike,
    name: string,
    place: string
  ];
  export type OutputTuple = [
    actorId: bigint,
    role: bigint,
    actor: string,
    name: string,
    place: string
  ];
  export interface OutputObject {
    actorId: bigint;
    role: bigint;
    actor: string;
    name: string;
    place: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchRecalledEvent {
  export type InputTuple = [
    productId: BigNumberish,
    manufacturer: AddressLike,
    reasonHash: BytesLike,
    deadline: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    manufacturer: string,
    reasonHash: string,
    deadline: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    manufacturer: string;
    reasonHash: string;
    deadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchRegisteredEvent {
  export type InputTuple = [
    productId: BigNumberish,
    manufacturer: AddressLike,
    quantity: BigNumberish,
    merkleRoot: BytesLike
  ];
  export type OutputTuple = [
    productId: bigint,
    manufacturer: string,
    quantity: bigint,
    merkleRoot: string
  ];
  export interface OutputObject {
    productId: bigint;
    manufacturer: string;
    quantity: bigint;
    merkleRoot: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductAddedEvent {
  export type InputTuple = [productId: BigNumberish, name: string];
  export type OutputTuple = [productId: bigint, name: string];
  export interface OutputObject {
    productId: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductStageUpdatedEvent {
  export type InputTuple = [productId: BigNumberish, stage: BigNumberish];
  export type OutputTuple = [productId: bigint, stage: bigint];
  export interface OutputObject {
    productId: bigint;
    stage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecallAcknowledgedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    holder: AddressLike,
    late: boolean
  ];
  export type OutputTuple = [productId: bigint, holder: string, late: boolean];
  export interface OutputObject {
    productId: bigint;
    holder: string;
    late: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecallEscalatedEvent {
  export type InputTuple = [productId: BigNumberish, holder: AddressLike];
  export type OutputTuple = [productId: bigint, holder: string];
  export interface OutputObject {
    productId: bigint;
    holder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecallWindowUpdatedEvent {
  export type InputTuple = [window: BigNumberish];
  export type OutputTuple = [window: bigint];
  export interface OutputObject {
    window: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnitClaimedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    serial: BigNumberish,
    claimant: AddressLike,
    beforeSale: boolean
  ];
  export type OutputTuple = [
    productId: bigint,
    serial: bigint,
    claimant: string,
    beforeSale: boolean
  ];
  export interface OutputObject {
    productId: bigint;
    serial: bigint;
    claimant: string;
    beforeSale: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnitsQuarantinedEvent {
  export type InputTuple = [
    productId: BigNumberish,
    holder: AddressLike,
    count: BigNumberish
  ];
  export type OutputTuple = [productId: bigint, holder: string, count: bigint];
  export interface OutputObject {
    productId: bigint;
    holder: string;
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SupplyChain extends BaseContract {
  connect(runner?: ContractRunner | null): SupplyChain;
  waitForDeployment(): Promise<this>;

  interface: SupplyChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DISTRIBUTORS: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;

  MAX_BATCH_QUANTITY: TypedContractMethod<[], [bigint], "view">;

  MAX_QUARANTINE_PER_TX: TypedContractMethod<[], [bigint], "view">;

  PRODUCERS: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;

  ProductStock: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        name: string;
        description: string;
        supplierId: bigint;
        producerId: bigint;
        distributorId: bigint;
        sellerId: bigint;
        stage: bigint;
        quantity: bigint;
        merkleRoot: string;
      }
    ],
    "view"
  >;

  SELLERS: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;

  SUPPLIERS: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;

  ackRecall: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  actorId: TypedContractMethod<
    [_address: AddressLike, _role: BigNumberish],
    [bigint],
    "view"
  >;

  addActor: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string, _role: BigNumberish],
    [void],
    "nonpayable"
  >;

  addDistributor: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addProducer: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addProduct: TypedContractMethod<
    [
      _name: string,
      _description: string,
      _quantity: BigNumberish,
      _merkleRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  addSeller: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  addSupplier: TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;

  claimDigest: TypedContractMethod<
    [_productId: BigNumberish, _serial: BigNumberish, _claimant: AddressLike],
    [string],
    "view"
  >;

  claimUnit: TypedContractMethod<
    [
      _productId: BigNumberish,
      _serial: BigNumberish,
      _secret: BytesLike,
      _proof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  claimUnitFor: TypedContractMethod<
    [
      _productId: BigNumberish,
      _serial: BigNumberish,
      _secret: BytesLike,
      _proof: BytesLike[],
      _claimant: AddressLike,
      _signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  claimedBeforeSaleCount: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  claimedCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  closureReport: TypedContractMethod<
    [_productId: BigNumberish],
    [SupplyChain.ClosureReportStructOutput],
    "view"
  >;

  distributeProduct: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributorCtr: TypedContractMethod<[], [bigint], "view">;

  escalate: TypedContractMethod<
    [_productId: BigNumberish, _holder: AddressLike],
    [void],
    "nonpayable"
  >;

  getRecallHolders: TypedContractMethod<
    [_productId: BigNumberish],
    [string[]],
    "view"
  >;

  holderStatus: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  listForSale: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  markProductSold: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  missedRecalls: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  processProduct: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  producerCtr: TypedContractMethod<[], [bigint], "view">;

  productCtr: TypedContractMethod<[], [bigint], "view">;

  quarantineUnits: TypedContractMethod<
    [_productId: BigNumberish, _serials: BigNumberish[]],
    [bigint],
    "nonpayable"
  >;

  quarantinedCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  recall: TypedContractMethod<
    [_productId: BigNumberish, _reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;

  recallWindow: TypedContractMethod<[], [bigint], "view">;

  recalls: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, string, bigint, bigint, string, bigint, bigint] & {
        active: boolean;
        initiatedBy: string;
        recalledAt: bigint;
        deadline: bigint;
        reasonHash: string;
        holdersAcknowledged: bigint;
        holdersEscalated: bigint;
      }
    ],
    "view"
  >;

  sellerCtr: TypedContractMethod<[], [bigint], "view">;

  setRecallWindow: TypedContractMethod<
    [_window: BigNumberish],
    [void],
    "nonpayable"
  >;

  showStage: TypedContractMethod<[_productId: BigNumberish], [string], "view">;

  supplierCtr: TypedContractMethod<[], [bigint], "view">;

  supplyProduct: TypedContractMethod<
    [_productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  unitLeaf: TypedContractMethod<
    [_serial: BigNumberish, _secret: BytesLike],
    [string],
    "view"
  >;

  unitStatus: TypedContractMethod<
    [
      _productId: BigNumberish,
      _serial: BigNumberish,
      _secret: BytesLike,
      _proof: BytesLike[]
    ],
    [[bigint, string] & { status: bigint; claimant: string }],
    "view"
  >;

  units: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, boolean] & {
        claimant: string;
        state: bigint;
        claimedBeforeSale: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DISTRIBUTORS"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "MAX_BATCH_QUANTITY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_QUARANTINE_PER_TX"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRODUCERS"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ProductStock"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: bigint;
        name: string;
        description: string;
        supplierId: bigint;
        producerId: bigint;
        distributorId: bigint;
        sellerId: bigint;
        stage: bigint;
        quantity: bigint;
        merkleRoot: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "SELLERS"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "SUPPLIERS"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, string, string, bigint] & {
        addr: string;
        id: bigint;
        name: string;
        place: string;
        role: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ackRecall"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "actorId"
  ): TypedContractMethod<
    [_address: AddressLike, _role: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "addActor"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string, _role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addDistributor"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addProducer"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addProduct"
  ): TypedContractMethod<
    [
      _name: string,
      _description: string,
      _quantity: BigNumberish,
      _merkleRoot: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addSeller"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addSupplier"
  ): TypedContractMethod<
    [_address: AddressLike, _name: string, _place: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimDigest"
  ): TypedContractMethod<
    [_productId: BigNumberish, _serial: BigNumberish, _claimant: AddressLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimUnit"
  ): TypedContractMethod<
    [
      _productId: BigNumberish,
      _serial: BigNumberish,
      _secret: BytesLike,
      _proof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimUnitFor"
  ): TypedContractMethod<
    [
      _productId: BigNumberish,
      _serial: BigNumberish,
      _secret: BytesLike,
      _proof: BytesLike[],
      _claimant: AddressLike,
      _signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimedBeforeSaleCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimedCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "closureReport"
  ): TypedContractMethod<
    [_productId: BigNumberish],
    [SupplyChain.ClosureReportStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "distributeProduct"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributorCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "escalate"
  ): TypedContractMethod<
    [_productId: BigNumberish, _holder: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRecallHolders"
  ): TypedContractMethod<[_productId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "holderStatus"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "listForSale"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "markProductSold"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "missedRecalls"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processProduct"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "producerCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "productCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "quarantineUnits"
  ): TypedContractMethod<
    [_productId: BigNumberish, _serials: BigNumberish[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "quarantinedCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "recall"
  ): TypedContractMethod<
    [_productId: BigNumberish, _reasonHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recallWindow"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "recalls"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [boolean, string, bigint, bigint, string, bigint, bigint] & {
        active: boolean;
        initiatedBy: string;
        recalledAt: bigint;
        deadline: bigint;
        reasonHash: string;
        holdersAcknowledged: bigint;
        holdersEscalated: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "sellerCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setRecallWindow"
  ): TypedContractMethod<[_window: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "showStage"
  ): TypedContractMethod<[_productId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "supplierCtr"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "supplyProduct"
  ): TypedContractMethod<[_productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unitLeaf"
  ): TypedContractMethod<
    [_serial: BigNumberish, _secret: BytesLike],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "unitStatus"
  ): TypedContractMethod<
    [
      _productId: BigNumberish,
      _serial: BigNumberish,
      _secret: BytesLike,
      _proof: BytesLike[]
    ],
    [[bigint, string] & { status: bigint; claimant: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "units"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, boolean] & {
        claimant: string;
        state: bigint;
        claimedBeforeSale: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "ActorAdded"
  ): TypedContractEvent<
    ActorAddedEvent.InputTuple,
    ActorAddedEvent.OutputTuple,
    ActorAddedEvent.OutputObject
  >;
  getEvent(
    key: "BatchRecalled"
  ): TypedContractEvent<
    BatchRecalledEvent.InputTuple,
    BatchRecalledEvent.OutputTuple,
    BatchRecalledEvent.OutputObject
  >;
  getEvent(
    key: "BatchRegistered"
  ): TypedContractEvent<
    BatchRegisteredEvent.InputTuple,
    BatchRegisteredEvent.OutputTuple,
    BatchRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProductAdded"
  ): TypedContractEvent<
    ProductAddedEvent.InputTuple,
    ProductAddedEvent.OutputTuple,
    ProductAddedEvent.OutputObject
  >;
  getEvent(
    key: "ProductStageUpdated"
  ): TypedContractEvent<
    ProductStageUpdatedEvent.InputTuple,
    ProductStageUpdatedEvent.OutputTuple,
    ProductStageUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RecallAcknowledged"
  ): TypedContractEvent<
    RecallAcknowledgedEvent.InputTuple,
    RecallAcknowledgedEvent.OutputTuple,
    RecallAcknowledgedEvent.OutputObject
  >;
  getEvent(
    key: "RecallEscalated"
  ): TypedContractEvent<
    RecallEscalatedEvent.InputTuple,
    RecallEscalatedEvent.OutputTuple,
    RecallEscalatedEvent.OutputObject
  >;
  getEvent(
    key: "RecallWindowUpdated"
  ): TypedContractEvent<
    RecallWindowUpdatedEvent.InputTuple,
    RecallWindowUpdatedEvent.OutputTuple,
    RecallWindowUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "UnitClaimed"
  ): TypedContractEvent<
    UnitClaimedEvent.InputTuple,
    UnitClaimedEvent.OutputTuple,
    UnitClaimedEvent.OutputObject
  >;
  getEvent(
    key: "UnitsQuarantined"
  ): TypedContractEvent<
    UnitsQuarantinedEvent.InputTuple,
    UnitsQuarantinedEvent.OutputTuple,
    UnitsQuarantinedEvent.OutputObject
  >;

  filters: {
    "ActorAdded(uint256,uint8,address,string,string)": TypedContractEvent<
      ActorAddedEvent.InputTuple,
      ActorAddedEvent.OutputTuple,
      ActorAddedEvent.OutputObject
    >;
    ActorAdded: TypedContractEvent<
      ActorAddedEvent.InputTuple,
      ActorAddedEvent.OutputTuple,
      ActorAddedEvent.OutputObject
    >;

    "BatchRecalled(uint256,address,bytes32,uint64)": TypedContractEvent<
      BatchRecalledEvent.InputTuple,
      BatchRecalledEvent.OutputTuple,
      BatchRecalledEvent.OutputObject
    >;
    BatchRecalled: TypedContractEvent<
      BatchRecalledEvent.InputTuple,
      BatchRecalledEvent.OutputTuple,
      BatchRecalledEvent.OutputObject
    >;

    "BatchRegistered(uint256,address,uint256,bytes32)": TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;
    BatchRegistered: TypedContractEvent<
      BatchRegisteredEvent.InputTuple,
      BatchRegisteredEvent.OutputTuple,
      BatchRegisteredEvent.OutputObject
    >;

    "ProductAdded(uint256,string)": TypedContractEvent<
      ProductAddedEvent.InputTuple,
      ProductAddedEvent.OutputTuple,
      ProductAddedEvent.OutputObject
    >;
    ProductAdded: TypedContractEvent<
      ProductAddedEvent.InputTuple,
      ProductAddedEvent.OutputTuple,
      ProductAddedEvent.OutputObject
    >;

    "ProductStageUpdated(uint256,uint8)": TypedContractEvent<
      ProductStageUpdatedEvent.InputTuple,
      ProductStageUpdatedEvent.OutputTuple,
      ProductStageUpdatedEvent.OutputObject
    >;
    ProductStageUpdated: TypedContractEvent<
      ProductStageUpdatedEvent.InputTuple,
      ProductStageUpdatedEvent.OutputTuple,
      ProductStageUpdatedEvent.OutputObject
    >;

    "RecallAcknowledged(uint256,address,bool)": TypedContractEvent<
      RecallAcknowledgedEvent.InputTuple,
      RecallAcknowledgedEvent.OutputTuple,
      RecallAcknowledgedEvent.OutputObject
    >;
    RecallAcknowledged: TypedContractEvent<
      RecallAcknowledgedEvent.InputTuple,
      RecallAcknowledgedEvent.OutputTuple,
      RecallAcknowledgedEvent.OutputObject
    >;

    "RecallEscalated(uint256,address)": TypedContractEvent<
      RecallEscalatedEvent.InputTuple,
      RecallEscalatedEvent.OutputTuple,
      RecallEscalatedEvent.OutputObject
    >;
    RecallEscalated: TypedContractEvent<
      RecallEscalatedEvent.InputTuple,
      RecallEscalatedEvent.OutputTuple,
      RecallEscalatedEvent.OutputObject
    >;

    "RecallWindowUpdated(uint64)": TypedContractEvent<
      RecallWindowUpdatedEvent.InputTuple,
      RecallWindowUpdatedEvent.OutputTuple,
      RecallWindowUpdatedEvent.OutputObject
    >;
    RecallWindowUpdated: TypedContractEvent<
      RecallWindowUpdatedEvent.InputTuple,
      RecallWindowUpdatedEvent.OutputTuple,
      RecallWindowUpdatedEvent.OutputObject
    >;

    "UnitClaimed(uint256,uint256,address,bool)": TypedContractEvent<
      UnitClaimedEvent.InputTuple,
      UnitClaimedEvent.OutputTuple,
      UnitClaimedEvent.OutputObject
    >;
    UnitClaimed: TypedContractEvent<
      UnitClaimedEvent.InputTuple,
      UnitClaimedEvent.OutputTuple,
      UnitClaimedEvent.OutputObject
    >;

    "UnitsQuarantined(uint256,address,uint256)": TypedContractEvent<
      UnitsQuarantinedEvent.InputTuple,
      UnitsQuarantinedEvent.OutputTuple,
      UnitsQuarantinedEvent.OutputObject
    >;
    UnitsQuarantined: TypedContractEvent<
      UnitsQuarantinedEvent.InputTuple,
      UnitsQuarantinedEvent.OutputTuple,
      UnitsQuarantinedEvent.OutputObject
    >;
  };
}
